### ISSUE TITLE
设置了header，并且设置了阴影的时候，header的位置从0,0开始布局，超出了阴影范围，能否从阴影边框开始布局呢

### ISSUE THREAD

**Issue by LYluyu** [kingjiajie/JJCollectionViewRoundFlowLayout#1]
如图
![image](https://user-images.githubusercontent.com/16254669/70030549-66399d00-15e4-11ea-8956-523f3739d78f.png)

**Comment by kingjiajie** [comment]
你好。设置阴影的时候是可以设置阴影的偏离量的，请问这个可以解决你之的问题么？白定义的代里里有一个设置阴影，和一个设置阴影偏移的代理。------------------ 原始邮件 ------------------
发件人: "LYluyu"<notifications@github.com>
发送时间: 2019年12月3日(星期二) 下午3:49
收件人: "kingjiajie/JJCollectionViewRoundFlowLayout"<JJCollectionViewRoundFlowLayout@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [kingjiajie/JJCollectionViewRoundFlowLayout] 设置了header，并且设置了阴影的时候，header的位置从0,0开始布局，超出了阴影范围，能否从阴影边框开始布局呢 (#1)



如图
 
 
&mdash;

**Comment by LYluyu** [comment]
您好，我试了代理方法borderEdgeInsertsForSectionAtIndex，效果不好，然后也试了一下JJCollectionViewRoundConfigModel的shadowOffset，还是不太好。

**Comment by kingjiajie** [comment]
可以详细描述一下你具体需求么 ？你是需要将headerview布局从系统设置的0,0  设置到其他例如 0,10 布局么？

**Comment by kingjiajie** [comment]
如果是上述设置的，在headerview上内嵌一个自定义view，然后设置你的自定义view的布局？这是否可以解决你的需求？

> 您好，我试了代理方法borderEdgeInsertsForSectionAtIndex，效果不好，然后也试了一下JJCollectionViewRoundConfigModel的shadowOffset，还是不太好。

**Comment by LYluyu** [comment]
感觉这样不太好，应该是框架这边去处理这个，正常来说应该是在背景框内去布局效果会好很多，比如背景的起点为xy都为10，如果有头部，头部应该也是从背景的xy开始布局；如果没有头部，应该是cell从背景的xy开始布局。这样就不会和UI给的图有太多出入。从我的图也可以看出，一超出背景，header的底部和cell的间距与顶部和背景的间距不相等。

**Comment by LYluyu** [comment]
我找到了一个https://github.com/xueyongwei/YRCollectionViewLayout，不知道能否参考一下？

**Comment by kingjiajie** [comment]
> 我找到了一个[https://github.com/xueyongwei/YRCollectionViewLayout，不知道能否参考一下？](https://github.com/xueyongwei/YRCollectionViewLayout%EF%BC%8C%E4%B8%8D%E7%9F%A5%E9%81%93%E8%83%BD%E5%90%A6%E5%8F%82%E8%80%83%E4%B8%80%E4%B8%8B%EF%BC%9F)

你好，我查看你提到的控件，我主要查看了他的“分区背景颜色”这个位置的显示，我也发现了他这个代码
```swift

    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, edgeInsetExtendedFor section: Int) -> UIEdgeInsets {
        
        return UIEdgeInsets.init(top: 10, left: 10, bottom: 10, right: 10)
    }
```

当你将他设置成  UIEdgeInsets.init(top: 0, left: 0 bottom: 0, right: 0)的时候，他的背景框的开始位置和cell开始位置是相同的。

我查看了他该方法的处理方法，这个设置也是设置背景的偏移量，但是他的偏移量是在他sectionInset基础上做向外扩张显示操作。 意思就是他的collectionview的layout已经设置了sectionInset了，所以cell的开始位置是sectionInset的位置，设置在

```swift
ListTableViewController.swift

 func getDemoController() -> UIViewController? {
        
        switch self {
        case .sectionBgColor:
            let layout = YRSectionBgColorFlowLayout()
            layout.scrollDirection = .vertical
            layout.itemSize = CGSize.init(width: 80, height: 80)
            layout.sectionInset = UIEdgeInsets.init(top: 20, left: 15, bottom: 20, right: 15)
            
            let vc = YRbgcCollectionViewController.init(collectionViewLayout: layout)
            return vc
        case .lineAlignLeft: ...

```

所以他设置0,0,0,0的时候，背景布局在cell开始的位置。

**Comment by kingjiajie** [comment]
> 我找到了一个[https://github.com/xueyongwei/YRCollectionViewLayout，不知道能否参考一下？](https://github.com/xueyongwei/YRCollectionViewLayout%EF%BC%8C%E4%B8%8D%E7%9F%A5%E9%81%93%E8%83%BD%E5%90%A6%E5%8F%82%E8%80%83%E4%B8%80%E4%B8%8B%EF%BC%9F)

我们的框架操作也是一样的，也是根据他的headerview，cell的原来布局，进行底色背景的添加。

但是我这边会进行一个操作就是，我会将layout.sectionInset的偏移补偿回去，就是如果他layout.sectionInset设置了 (10,10,10,10),    如果borderEdgeInsertsForSectionAtIndex 设置（0,0,0,0）的话，就会出现背景和cell有10间距。
出现这个的原因是我做了sectionInset 的补偿操作。 为了更好的自定义背景的位置偏移。

我的框架如果使用如下代码，也能实现对应视觉效果。代码如下：（测试VC为：“CollectionView（包住section圆角）”列）

```obj-c
- (UIEdgeInsets)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout insetForSectionAtIndex:(NSInteger)section{

    return UIEdgeInsetsMake(20, 20, 20, 20);
}


- (UIEdgeInsets)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout*)collectionViewLayout borderEdgeInsertsForSectionAtIndex:(NSInteger)section{
    return UIEdgeInsetsMake(20, 20, 20, 20);
}


```

如果没有headerview情况下，只要borderEdgeInsertsForSectionAtIndex 的设置与sectionInset设置相等，背景图起始位置也是cell的起始位置。

另外需要注意的是，如果有headerview或者footerview ，sectionInset的设置会影响到 headerview底部、footerview顶部与cell的间距， sectionInset 的 top 和bottom分别是cell与headerview的间距和cell与footerview的间距。  所以如果有headerview或者footerview，  borderEdgeInsertsForSectionAtIndex 的top和bottom设置为0， 例如(0, 20, 0, 20)，就能在header开始，footerview结束了。

**Comment by LYluyu** [comment]
好的，非常感谢

**Comment by LYluyu** [comment]
@kingjiajie 老哥，您好，每一组数据都存在headerView且header布局一样的时候，如果我想第一组顶部留点间隙，最后一组底部留点间隙，用您说的这两个代理方法，会出现第一组超出了边框。请问这个怎么处理呢。

**Comment by kingjiajie** [comment]
你截图一下看看你需要的效果是怎么样的， 然后我这边显示的内容是怎么样的呢， 因为我现在不怎么理解你说超出边框的内容是什么哦

**Comment by kingjiajie** [comment]
> @kingjiajie 老哥，您好，每一组数据都存在headerView且header布局一样的时候，如果我想第一组顶部留点间隙，最后一组底部留点间隙，用您说的这两个代理方法，会出现第一组超出了边框。请问这个怎么处理呢。

你截图一下看看你需要的效果是怎么样的， 然后我这边显示的内容是怎么样的呢， 因为我现在不怎么理解你说超出边框的内容是什么哦

**Comment by LYluyu** [comment]
![image](https://user-images.githubusercontent.com/16254669/70691835-05e9e000-1cf5-11ea-87c0-5dde152a00a7.png)
您看看，如图，collectionView代码如下，其中kPrimaryMargin为10
`- (UIEdgeInsets)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout*)collectionViewLayout borderEdgeInsertsForSectionAtIndex:(NSInteger)section{
    if (section == 0) {
        return UIEdgeInsetsMake(kPrimaryMargin, kPrimaryMargin, kPrimaryMargin, kPrimaryMargin);
    }
    return UIEdgeInsetsMake(0, kPrimaryMargin, 0, kPrimaryMargin);
}
`

**Comment by LYluyu** [comment]
第一组设置了insert的top为10，边框正常的离顶部有10的间距了，但是我设置header的时候，还是超出去了。

**Comment by kingjiajie** [comment]
> ![image](https://user-images.githubusercontent.com/16254669/70691835-05e9e000-1cf5-11ea-87c0-5dde152a00a7.png)
> 您看看，如图，collectionView代码如下，其中kPrimaryMargin为10
> `- (UIEdgeInsets)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout*)collectionViewLayout borderEdgeInsertsForSectionAtIndex:(NSInteger)section{ if (section == 0) { return UIEdgeInsetsMake(kPrimaryMargin, kPrimaryMargin, kPrimaryMargin, kPrimaryMargin); } return UIEdgeInsetsMake(0, kPrimaryMargin, 0, kPrimaryMargin); }`

你说的insert 是sectionInsert 的top = 10吗， 如果是sectioninsert的话，那么这个数值设置的是headerview与cell的间距， 和第一个headerview与顶部nav栏的距离是无关的哦。
如果没有headerview的话，那么就是cell与顶部距离了。

如果你现在是想第一个headerview没有超出round底色 ， 那么if (section == 0) { return UIEdgeInsetsMake(0, kPrimaryMargin, kPrimaryMargin, kPrimaryMargin); } 就可以了，borderEdgeInserts是在headerview的0，0开始计算，所以borderEdgeInserts 设置top，headerview突出了底色。

**Comment by kingjiajie** [comment]
> 第一组设置了insert的top为10，边框正常的离顶部有10的间距了，但是我设置header的时候，还是超出去了。

你看看我刚刚说的是否可以解决你的问题。

**Comment by kingjiajie** [comment]
> 第一组设置了insert的top为10，边框正常的离顶部有10的间距了，但是我设置header的时候，还是超出去了。

你看看我上面说是否可以解决到你的疑惑。

**Comment by kingjiajie** [comment]
> 第一组设置了insert的top为10，边框正常的离顶部有10的间距了，但是我设置header的时候，还是超出去了。

你或者因为你有设置headerview，所以collectionview的sectionInserts设置了top是headerview和cell的距离，你设置了headerview的话，那么headerview就会与顶部没有间隙了，你可以单独设置的一个headerview的高度 + 10 ，然后borderEdgeInserts 第一个top为10，这样就可以了。 然后你底部设置insert有间隙，是因为你没有footerview，所以是cell与底部有间隙了。

**Comment by LYluyu** [comment]
@kingjiajie 可否加我QQ呀？76814394

**Comment by kingjiajie** [comment]
> @kingjiajie 可否加我QQ呀？76814394

兄弟，你这个QQ要验证问题才能加，你加我吧。

2857184785
