### ISSUE TITLE
IGListkit4.0.0 - ListBindingSectionController 圆角没起作用，3q

### ISSUE THREAD

**Issue by BeingCode** [kingjiajie/JJCollectionViewRoundFlowLayout#10]

**Comment by kingjiajie** [comment]
好的，感谢反馈，我这边先查看一下。

**Comment by BeingCode** [comment]
@kingjiajie 3q

**Comment by kingjiajie** [comment]
您好，我讲demo中，改成如下pod配置（此前IGListKit版本为2.1.0）
`platform :ios, '9.0'
pod 'IGListKit', '~> 4.0.0'  
`

在MyIGListSectionController 文件继承改成IGListBindingSectionController后（此前是继承IGListSectionController），
讲IGListSectionType 修改修改成新的IGListAdapterDataSource后，是可以正常设置底色相关，包括问题提到的圆角。暂时没出现问题。

请问您这边方便提供一下详细的布局等等的信息或者demo么？我在详细查看是否哪个位置出现问题了。
再次感谢您的反馈。

**Comment by BeingCode** [comment]
@kingjiajie 你把你改过麻烦发我一下，我这样处理是不行的

**Comment by kingjiajie** [comment]
> @kingjiajie 你把你改过麻烦发我一下，我这样处理是不行的

我将修改的代码重新打包了一个网盘的，您这边可以下载尝试一下。入口也是以前demo的入口
链接: https://pan.baidu.com/s/1QEpKoHTc-qdiRPsXL1ewAg 提取码: z8u4 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by BeingCode** [comment]
@kingjiajie 发现问题了，当背景和cell一样大小的时候虽然设置了圆角但是体现不出来，因为背景在cell下面被遮挡了，

**Comment by kingjiajie** [comment]
> @kingjiajie 发现问题了，当背景和cell一样大小的时候虽然设置了圆角但是体现不出来，因为背景在cell下面被遮挡了，

找到问题就好，在这种情况可以设置偏移量，可以让背景进行偏移，向外扩展，这样cell就不会遮挡底色了， 但是要注意的是，向外扩展不能超出本来tableview或collectionview的范围，不然也是看不到。被裁剪了。

**Comment by BeingCode** [comment]
@kingjiajie 3q
