### ISSUE TITLE
组背景色在切后台再回到前台会失效

### ISSUE THREAD

**Issue by wangyunw** [kingjiajie/JJCollectionViewRoundFlowLayout#12]
JJCollectionViewRoundConfigModel
设置背景颜色   在ios15和14上面  进入后台 几秒钟再进入前台会出现背景色失效

**Comment by kingjiajie** [comment]
> 

您好，感谢您的反馈，我排查一下。

**Comment by kingjiajie** [comment]
> JJCollectionViewRoundConfigModel
> 设置背景颜色 在ios15和14上面 进入后台 几秒钟再进入前台会出现背景色失效

您好，经过多个版本和一系列的尝试，暂时没发现您对应的问题，是否可以描述一下，使用的设备和iOS的系统版本呢？ 我这边使用真机15.5、14、模拟器15.5版本都没出现对应问题。

**Comment by wangyunw** [comment]
> > JJCollectionViewRoundConfigModel
> > 设置背景颜色 在ios15和14上面 进入后台 几秒钟再进入前台会出现背景色失效
> 
> 您好，经过多个版本和一系列的尝试，暂时没发现您对应的问题，是否可以描述一下，使用的设备和iOS的系统版本呢？ 我这边使用真机15.5、14、模拟器15.5版本都没出现对应问题。

刚再次运行了下之前项目 发现无法复现了  下次我再观察

**Comment by kingjiajie** [comment]
> > > JJCollectionViewRoundConfigModel
> > > 设置背景颜色 在ios15和14上面 进入后台 几秒钟再进入前台会出现背景色失效
> > 
> > 
> > 您好，经过多个版本和一系列的尝试，暂时没发现您对应的问题，是否可以描述一下，使用的设备和iOS的系统版本呢？ 我这边使用真机15.5、14、模拟器15.5版本都没出现对应问题。
> 
> 刚再次运行了下之前项目 发现无法复现了 下次我再观察

那好的，那我先将问题关了，如果后续有相同的问题，可以重启该issues。谢谢
