### ISSUE TITLE
瀑布流

### ISSUE THREAD

**Issue by bbtyou** [kingjiajie/JJCollectionViewRoundFlowLayout#13]
请问现在支持瀑布流模式吗？

**Comment by kingjiajie** [comment]
> 请问现在支持瀑布流模式吗？

您好，现在暂时还不支持瀑布流模式，有计划添加，时间暂时还没确定，因为瀑布流模式有比较多需要解决问题。

**Comment by bbtyou** [comment]
好的，感谢。我使用[ZLCollectionViewFlowLayout](https://github.com/czl0325/ZLCollectionView)实现了。
