### ISSUE TITLE
2.9.1 设置顶部悬浮 会崩溃

### ISSUE THREAD

**Issue by wangchunjiang** [kingjiajie/JJCollectionViewRoundFlowLayout#14]
设置 layout.sectionHeadersPinToVisibleBounds = YES ,滑动崩溃,demo 必现

**Comment by kingjiajie** [comment]
> 

您好，我这边马上进行排查。谢谢反馈

**Comment by kingjiajie** [comment]
> 设置 layout.sectionHeadersPinToVisibleBounds = YES ,滑动崩溃,demo 必现

您好，在排查中发现，旧版本2.9.0及一下暂时能够正常运行，如遇到对应情况的小伙伴，先将版本降级到2.9.0及以下版本，暂不影响使用，因为2.9.1版本修复了一下特定情况下出现的夜间模式和白天模式切换的问题。给您做成不便，抱歉

这边继续排查，然后及时进行修复。

**Comment by wangchunjiang** [comment]
感谢作者及时回复,目前已降回2.9.0



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月22日(星期三) 上午9:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kingjiajie/JJCollectionViewRoundFlowLayout] 2.9.1 设置顶部悬浮 会崩溃 (Issue #14)





  
设置 layout.sectionHeadersPinToVisibleBounds = YES ,滑动崩溃,demo 必现
  
您好，在排查中发现，旧版本2.9.0及一下暂时能够正常运行，如遇到对应情况的小伙伴，先将版本降级到2.9.0及以下版本，暂不影响使用，因为2.9.1版本修复了一下特定情况下出现的夜间模式和白天模式切换的问题。给您做成不便，抱歉
 
这边继续排查，然后及时进行修复。
