### ISSUE TITLE
JJCollectionViewRoundFlowLayout 未设置SectionFooter异常

### ISSUE THREAD

**Issue by fengshh93** [kingjiajie/JJCollectionViewRoundFlowLayout#15]
我设置了SectionHeader 但是不需要SectionFooter我就未设置，部分机型就出现异常
UICollectionView internal inconsistency: missing final attributes for supplementary <JJCollectionReusableView: 0x1319567a0; baseClass = UICollectionReusableView; frame = (0 336.333; 428 153.977); backgroundColor = UIExtendedGrayColorSpace 1 1; layer = <CALayer: 0x2812efcc0>>; initial attributes: <JJCollectionViewRoundLayoutAttributes: 0x131956f50> index path: (2-0); element kind: ((null)); frame = (0 336.333; 428 153.977); zIndex = -1; ; layout query: (null); collection view: <UICollectionView: 0x105a6c800; frame = (0 0; 428 926); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x281c67810>; backgroundColor = UIExtendedSRGBColorSpace 0.972549 0.972549 0.972549 1; layer = <CALayer: 0x281203b20>; contentOffset: {0, -91}; contentSize: {428, 490.37931034482756}; adjustedContentInset: {91, 0, 134.79310344827587, 0}; layout: <JJCollectionViewRoundFlowLayout: 0x1319e6890>; dataSource: <ATSearchFilterViewController: 0x10571aa80>>

**Comment by kingjiajie** [comment]
> 我设置了SectionHeader 但是不需要SectionFooter我就未设置，部分机型就出现异常
> UICollectionView internal inconsistency: missing final attributes for supplementary <JJCollectionReusableView: 0x1319567a0; baseClass = UICollectionReusableView; frame = (0 336.333; 428 153.977); backgroundColor = UIExtendedGrayColorSpace 1 1; layer = <CALayer: 0x2812efcc0>>; initial attributes: <JJCollectionViewRoundLayoutAttributes: 0x131956f50> index path: (2-0); element kind: ((null)); frame = (0 336.333; 428 153.977); zIndex = -1; ; layout query: (null); collection view: <UICollectionView: 0x105a6c800; frame = (0 0; 428 926); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x281c67810>; backgroundColor = UIExtendedSRGBColorSpace 0.972549 0.972549 0.972549 1; layer = <CALayer: 0x281203b20>; contentOffset: {0, -91}; contentSize: {428, 490.37931034482756}; adjustedContentInset: {91, 0, 134.79310344827587, 0}; layout: <JJCollectionViewRoundFlowLayout: 0x1319e6890>; dataSource: <ATSearchFilterViewController: 0x10571aa80>>

您好，我这边查看一下，可以发送一下机型信息么？我去排查一下。

**Comment by kingjiajie** [comment]
> 我设置了SectionHeader 但是不需要SectionFooter我就未设置，部分机型就出现异常
> UICollectionView internal inconsistency: missing final attributes for supplementary <JJCollectionReusableView: 0x1319567a0; baseClass = UICollectionReusableView; frame = (0 336.333; 428 153.977); backgroundColor = UIExtendedGrayColorSpace 1 1; layer = <CALayer: 0x2812efcc0>>; initial attributes: <JJCollectionViewRoundLayoutAttributes: 0x131956f50> index path: (2-0); element kind: ((null)); frame = (0 336.333; 428 153.977); zIndex = -1; ; layout query: (null); collection view: <UICollectionView: 0x105a6c800; frame = (0 0; 428 926); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x281c67810>; backgroundColor = UIExtendedSRGBColorSpace 0.972549 0.972549 0.972549 1; layer = <CALayer: 0x281203b20>; contentOffset: {0, -91}; contentSize: {428, 490.37931034482756}; adjustedContentInset: {91, 0, 134.79310344827587, 0}; layout: <JJCollectionViewRoundFlowLayout: 0x1319e6890>; dataSource: <ATSearchFilterViewController: 0x10571aa80>>

请问使用的库版本是多少？

**Comment by fengshh93** [comment]
设备iPhone 12 Pro Max 和 iPhone XS Max  系统都是16.0 现在线上用的库是2.9.1

**Comment by kingjiajie** [comment]
> 设备iPhone 12 Pro Max 和 iPhone XS Max 系统都是16.0 现在线上用的库是2.9.1

您好，请更新一下最新版本2.9.2版本。尝试一下，因为2.9.2版本修复了该问题了。
