### ISSUE TITLE
在iPhone7或者 iPhone7plus的 iOS系统12.4上滑动就闪退

### ISSUE THREAD

**Issue by RiversMaJianCheng** [kingjiajie/JJCollectionViewRoundFlowLayout#17]
*** Assertion failure in -[UICollectionViewData validateLayoutInRect:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3698.140/UICollectionViewData.m:459

**Comment by kingjiajie** [comment]
> *** Assertion failure in -[UICollectionViewData validateLayoutInRect:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3698.140/UICollectionViewData.m:459

您好，请问使用的是哪一版本的库呢？

**Comment by RiversMaJianCheng** [comment]
- JJCollectionViewRoundFlowLayout (2.9.2) 这个版本

**Comment by RiversMaJianCheng** [comment]
> > *** Assertion failure in -[UICollectionViewData validateLayoutInRect:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3698.140/UICollectionViewData.m:459
> 
> 您好，请问使用的是哪一版本的库呢？

 - JJCollectionViewRoundFlowLayout (2.9.2) 您好，是这个版本

**Comment by kingjiajie** [comment]
> > > *** Assertion failure in -[UICollectionViewData validateLayoutInRect:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3698.140/UICollectionViewData.m:459
> > 
> > 
> > 您好，请问使用的是哪一版本的库呢？
> 
> * JJCollectionViewRoundFlowLayout (2.9.2) 您好，是这个版本

好，我先去排查一下。

**Comment by RiversMaJianCheng** [comment]
> > > > *** Assertion failure in -[UICollectionViewData validateLayoutInRect:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3698.140/UICollectionViewData.m:459
> > > 
> > > 
> > > 您好，请问使用的是哪一版本的库呢？
> > 
> > 
> > 
> > * JJCollectionViewRoundFlowLayout (2.9.2) 您好，是这个版本
> 
> 好，我先去排查一下。

辛苦大佬了，麻烦好了告知一下哈，我这线上出问题了

**Comment by RiversMaJianCheng** [comment]
> > > > *** Assertion failure in -[UICollectionViewData validateLayoutInRect:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3698.140/UICollectionViewData.m:459
> > > 
> > > 
> > > 您好，请问使用的是哪一版本的库呢？
> > 
> > 
> > 
> > * JJCollectionViewRoundFlowLayout (2.9.2) 您好，是这个版本
> 
> 好，我先去排查一下。

我是一个uicollectionview里面第一个cell是标签用的是左对齐方式，其他cell的图片用的是正常的平分布局方式。相当于你的项目中第一组和第二组混合使用的，只有header没有footer，全包裹的。

**Comment by RiversMaJianCheng** [comment]
> 

最新发现如果用 JJCollectionViewFlowLayoutAlignmentTypeBySystem 布局就没问题，其他几个都会闪退

**Comment by kingjiajie** [comment]
> 最新发现如果用 JJCollectionViewFlowLayoutAlignmentTypeBySystem 布局就没问题，其他几个都会闪退

您好，根据你这边的描述，我在我的demo上操作，在SeventhViewController上添加如下代码。


```
JJCollectionViewRoundFlowLayout *layout = [[JJCollectionViewRoundFlowLayout alloc]init];
layout.isCalculateHeader = YES;  
```

```
        #pragma mark - header&footer  
  
        - (CGSize)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout referenceSizeForHeaderInSection:(NSInteger)section{
            return CGSizeMake(100, 60);
        }

        - (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath{
            MyCollectionReusableView *view = [collectionView dequeueReusableSupplementaryViewOfKind:kind withReuseIdentifier:NSStringFromClass([MyCollectionReusableView class]) forIndexPath:indexPath];
            if ([kind isEqualToString:UICollectionElementKindSectionHeader]) {
                view.myLabel.text = @"Header";
                return view;
            }else{
                view.myLabel.text = @"Footer";
                return view;
            }
        }

```

由于手上设备限制，没有对应提供的设备版本，使用的是模拟器， iPhone7 Plus  12.4版本。

暂时没发现对应问题。是否可以提供更详细的操作，或者提供demo我这边查看呢？

**Comment by kingjiajie** [comment]
对应的是demo的这一项
<img width="377" alt="image" src="https://user-images.githubusercontent.com/3367538/189304151-17122110-e9fd-4f92-896c-99594befab5b.png">

**Comment by RiversMaJianCheng** [comment]
> > 最新发现如果用 JJCollectionViewFlowLayoutAlignmentTypeBySystem 布局就没问题，其他几个都会闪退
> 
> 您好，根据你这边的描述，我在我的demo上操作，在SeventhViewController上添加如下代码。
> 
> ```
> JJCollectionViewRoundFlowLayout *layout = [[JJCollectionViewRoundFlowLayout alloc]init];
> layout.isCalculateHeader = YES;  
> ```
> 
>  ```
>         #pragma mark - header&footer  
>   
>         - (CGSize)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout referenceSizeForHeaderInSection:(NSInteger)section{
>             return CGSizeMake(100, 60);
>         }
> 
>         - (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath{
>             MyCollectionReusableView *view = [collectionView dequeueReusableSupplementaryViewOfKind:kind withReuseIdentifier:NSStringFromClass([MyCollectionReusableView class]) forIndexPath:indexPath];
>             if ([kind isEqualToString:UICollectionElementKindSectionHeader]) {
>                 view.myLabel.text = @"Header";
>                 return view;
>             }else{
>                 view.myLabel.text = @"Footer";
>                 return view;
>             }
>         }
> ```
> 
> 由于手上设备限制，没有对应提供的设备版本，使用的是模拟器， iPhone7 Plus 12.4版本。
> 
> 暂时没发现对应问题。是否可以提供更详细的操作，或者提供demo我这边查看呢？

非常感谢我到公司试试哈
