### ISSUE TITLE
邮箱留错留

### ISSUE THREAD

**Issue by zxr123** [kingjiajie/JJCollectionViewRoundFlowLayout#2]
邮箱是不是留错留,发送不留信息

**Comment by kingjiajie** [comment]
你好，邮箱正常使用的，可以正常进行联系，谢谢，你的邮件我已经回复了。

**Comment by kingjiajie** [comment]
非常抱歉，邮箱的确是有问题的，已经修改回来了。kingjiajie@sina.com。  感谢你指出该问题。
