### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by MondoYang** [kingjiajie/JJCollectionViewRoundFlowLayout#3]
因为cocoapods原因，
我是直接把文件导入项目中，使用#import "JJCollectionViewRoundFlowLayout.h"
其它一切正常，就是不走代理方法。有什么解决方案？

**Comment by kingjiajie** [comment]
请问你是所有代理都不走吗？ 你能提供一下你的大概的配置代码么？

**Comment by kingjiajie** [comment]
[百度网盘](https://pan.baidu.com/s/1UAsdNO9WX7rTJymz4oRMJA)
 密码:7qgh

我重新做了一个demo，demo是直接将库复制到自己项目中的。你可以参照一下。

**Comment by kingjiajie** [comment]
> 因为cocoapods原因，
> 我是直接把文件导入项目中，使用#import "JJCollectionViewRoundFlowLayout.h"
> 其它一切正常，就是不走代理方法。有什么解决方案？

你其它的正常CollectionView系统代理有走么？

**Comment by MondoYang** [comment]
> > 因为cocoapods原因，
> > 我是直接把文件导入项目中，使用#import "JJCollectionViewRoundFlowLayout.h"
> > 其它一切正常，就是不走代理方法。有什么解决方案？
> 
> 你其它的正常CollectionView系统代理有走么？

其它的代理都走的，我先看看你的demo，感谢！

**Comment by MondoYang** [comment]
找到原因了，因为我的CollectionView是用xib画的，FlowLayou没有应用。

**Comment by MondoYang** [comment]
谢谢作者的付出。哈哈😝

**Comment by kingjiajie** [comment]
> 谢谢作者的付出。哈哈😝

问题解决了就好，你用的时候有什么建议等等的，都可以反馈给我哦。

**Comment by loveuqian** [comment]
![图片](https://user-images.githubusercontent.com/9745332/89027006-48336080-d35c-11ea-9e13-8c725a302688.png)

他这个问题应该这里导致的，通过 xib 设置 flowlayout 的话，不会走 init 方法，所以没效果

**Comment by kingjiajie** [comment]
> ![图片](https://user-images.githubusercontent.com/9745332/89027006-48336080-d35c-11ea-9e13-8c725a302688.png)
> 
> 他这个问题应该这里导致的，通过 xib 设置 flowlayout 的话，不会走 init 方法，所以没效果

他这个也是因为xib生成后，没有将layout重新设置。这个因为xib默认设置的是UICollectionViewFlowLayout，走的是系统自己本来的代理。用xib创建了之后，可以通过setCollectionViewLayout重新设置成JJCollectionViewRoundFlowLayout。这样就可以进入代码了。

**Comment by loveuqian** [comment]
![图片](https://user-images.githubusercontent.com/9745332/89032946-4c657b00-d368-11ea-8fb3-36fb0d013e1e.png)

我是指在 xib 里创建 collectionView，直接可以在这里设置使用自定义 layout 的
如果这样设置的话，不会走 layout 的 init 方法

**Comment by kingjiajie** [comment]
> ![图片](https://user-images.githubusercontent.com/9745332/89032946-4c657b00-d368-11ea-8fb3-36fb0d013e1e.png)
> 
> 我是指在 xib 里创建 collectionView，直接可以在这里设置使用自定义 layout 的
> 如果这样设置的话，不会走 layout 的 init 方法

感谢你的反馈，我看了下，也发现了你说到的这个问题了，因为比较少使用xib，所以没发现该问题。
后面我会更新代码
`- (void)awakeFromNib{
    [super awakeFromNib];  
    _isRoundEnabled = YES;  
}`
现在如果使用的话，可以手动设置一下isRoundEnabled = YES， 我后续更新代码。
