### ISSUE TITLE
能否给背景添加点击事件

### ISSUE THREAD

**Issue by ccccccccai** [kingjiajie/JJCollectionViewRoundFlowLayout#4]
能否给背景添加点击事件

**Comment by kingjiajie** [comment]
> 能否给背景添加点击事件

你好，可以描述一下具体的点击事件的触发条件么？
例如，点击背景触发，只需要点击到背景范围触发等等的。

**Comment by kingjiajie** [comment]
> 能否给背景添加点击事件

刚好给你加上了点击事件响应了。 2.4.0版本的。
