### ISSUE TITLE
你好，我发现了一个在cell左对齐下卡片背景颜色算错的问题。

### ISSUE THREAD

**Issue by x1726919** [kingjiajie/JJCollectionViewRoundFlowLayout#5]
在您的demo中，cell对齐方式的分类，如在“CollectionView,有sections底色，cell左对齐”类目，也就是在对应工程“FourthViewController.m”里，修改_myDataArr参数为，2个短cell中间夹杂一个长cell，例如修改成：
_myDataArr = ({
        NSMutableArray *arr = [NSMutableArray arrayWithCapacity:0];
        [arr addObject:@"Hello"];
        [arr addObject:@"这个东西就是很长，就想弄一个很长的出来"];
        [arr addObject:@"Hello"];
        arr;
    });
section卡片的背景色frame也就是JJCollectionViewRoundLayoutAttributes的frame会计算错误。我大概看了下，可能是先算了这个frame，再整理对齐导致（可能是其他原因，因为比较忙没有仔细看，见谅。）。
最后谢谢提供一个非常漂亮的工具。

**Comment by kingjiajie** [comment]
> 在您的demo中，cell对齐方式的分类，如在“CollectionView,有sections底色，cell左对齐”类目，也就是在对应工程“FourthViewController.m”里，修改_myDataArr参数为，2个短cell中间夹杂一个长cell，例如修改成：
> _myDataArr = ({
> NSMutableArray *arr = [NSMutableArray arrayWithCapacity:0];
> [arr addObject:@"Hello"];
> [arr addObject:@"这个东西就是很长，就想弄一个很长的出来"];
> [arr addObject:@"Hello"];
> arr;
> });
> section卡片的背景色frame也就是JJCollectionViewRoundLayoutAttributes的frame会计算错误。我大概看了下，可能是先算了这个frame，再整理对齐导致（可能是其他原因，因为比较忙没有仔细看，见谅。）。
> 最后谢谢提供一个非常漂亮的工具。

您好，我先查看一下该问题哈。

**Comment by kingjiajie** [comment]
您好，已发现问题所在，正在构思解决方案。

**Comment by kingjiajie** [comment]
> 在您的demo中，cell对齐方式的分类，如在“CollectionView,有sections底色，cell左对齐”类目，也就是在对应工程“FourthViewController.m”里，修改_myDataArr参数为，2个短cell中间夹杂一个长cell，例如修改成：
> _myDataArr = ({
> NSMutableArray *arr = [NSMutableArray arrayWithCapacity:0];
> [arr addObject:@"Hello"];
> [arr addObject:@"这个东西就是很长，就想弄一个很长的出来"];
> [arr addObject:@"Hello"];
> arr;
> });
> section卡片的背景色frame也就是JJCollectionViewRoundLayoutAttributes的frame会计算错误。我大概看了下，可能是先算了这个frame，再整理对齐导致（可能是其他原因，因为比较忙没有仔细看，见谅。）。
> 最后谢谢提供一个非常漂亮的工具。

感谢您的反馈，在定位问题的时候，你这边说得多的，项目内容逻辑也是（是先算了这个frame，再整理对齐）。
但是导致该问题的不是顺序的问题，因为计算底色和对齐方式，是两个独立的模块，大家负责的内容是互不影响的。
问题导致的主要原因是：
collectionview 系统默认排版的内部逻辑，竖向显示的时候，"一行能够显示2个或以上的时候，系统默认会将该行第一个cell放到显示的最左边，该行最后一个可显示的cell放到显示的最右边。"，即当cell为2个时，大小为10，10，cell-1会显示在最左边，cell-2显示在最右边。这种情况下，计算不会出现问题，因为cell-1初始状态是在最左边位置。 

但当“因为cell-2太大，系统必须将cell-2换到下一行，即cell-1在第一行，cell-2在第二行的时候，cell-1会被系统居中显示”该情况下，计算就出现问题，初始数值在居中状态，所以出现上述问题。

最后，问题已解决。感谢。

**Comment by x1726919** [comment]
我还以为设计意图是计算（对齐后的）cell的frame来确定底色范围，然后因为一开始是居中导致意料之外的结果，抱歉项目时间太紧，没细看。
另外感谢作者这么耐心负责的回复，并讲述设计思路和原理，学到了很多。

**Comment by kingjiajie** [comment]
> 我还以为设计意图是计算（对齐后的）cell的frame来确定底色范围，然后因为一开始是居中导致意料之外的结果，抱歉项目时间太紧，没细看。
> 另外感谢作者这么耐心负责的回复，并讲述设计思路和原理，学到了很多。

项目版本已更新到2.5.1。可以pod更新后，该问题就修复了。
还是感谢您发现了该问题。让项目更完善。
