### ISSUE TITLE
感谢作者，不过貌似阴影效果很奇怪

### ISSUE THREAD

**Issue by Derkin** [kingjiajie/JJCollectionViewRoundFlowLayout#9]
添加阴影后，阴影是向上下垂直发散的，我看了半天代码也没看懂为何会这样，赶项目就没深入去研究了 
还有pod install 会报错，说是
You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by switching back to a branch.
我是未指定install版本的，有可能是我的source源的问题吧，不是很清楚，我赶项目就选择了拖拽到工程内容了

**Comment by kingjiajie** [comment]
您好，主要设置的地方是这里的
```
/// 投影相关参数
@property (nonatomic, strong) UIColor *shadowColor;
@property (nonatomic, assign) CGSize shadowOffset;
@property (nonatomic, assign) CGFloat shadowOpacity;
@property (nonatomic, assign) CGFloat shadowRadius;

```

设置这几个地方，属性是layer里面的，可以设置投影的偏移量等等的。
致于您返回后面的问题，我再查看一下我这边是否有出现对应的信息。

**Comment by kingjiajie** [comment]
请问以上的属性是达到你的需求了，如果达到的话，我这边就将这个issue关闭了哦
